TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b
PDL_BASE_URL: https://pdl-api.prod-fss-pub.nais.io/graphql
PDL_SCOPE: prod-fss.pdl.pdl-api
SKJERMEDE_BASE_URL: https://skjermede-personer-pip.intern.nav.no

NORG2_API_V1_URL: https://norg2.prod-fss-pub.nais.io/norg2/api/v1
PROXY_APP_CLIENT_ID: 981be1fb-1379-465f-bddc-7563197aed84

REGOPPSLAG_URL: https://regoppslag.prod-fss-pub.nais.io
REGOPPSLAG_SCOPE: prod-fss.teamdokumenthandtering.regoppslag

EREG_URL: https://ereg-services.prod-fss-pub.nais.io/api/v2

DOK_DIST_KANAL_URL: https://dokdistkanal.prod-fss-pub.nais.io
DOK_DIST_KANAL_SCOPE: prod-fss.teamdokumenthandtering.dokdistkanal

KODEVERK_API_URL: https://kodeverk-api.nav.no/api/v1/kodeverk
KODEVERK_SCOPE: prod-gcp.team-rocket.kodeverk-api

VEDTAK_FATTET_TOPIC: klage.vedtak-fattet.v1
DVH_STATISTIKK_TOPIC: klage.kabal-statistikk.v1
BEHANDLING_ENDRET_TOPIC_V2: klage.behandling-endret.v2
BEHANDLING_EVENTS_TOPIC: klage.behandling-events.v1

KRR_PROXY_REST_URL: https://digdir-krr-proxy.intern.nav.no/
KRR_PROXY_SCOPE: prod-gcp.team-rocket.digdir-krr-proxy

AIVEN_ES_HOST: elastic-klage-oppgave-es-nav-prod.aivencloud.com
AIVEN_ES_PORT: 26482
AIVEN_ES_SCHEME: https
AIVEN_ES_USE_SSL: true

NOM_BASE_URL: https://nom-api.intern.nav.no/graphql
NOM_SCOPE: prod-gcp.nom.nom-api

SAF_BASE_URL: https://saf.prod-fss-pub.nais.io/
SAF_SCOPE: prod-fss.teamdokumenthandtering.saf

DOKARKIV_SCOPE: prod-fss.teamdokumenthandtering.dokarkiv/
DOKARKIV_BASE_URL: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1

CLAM_AV_URL: http://clamav.nais-system/scan

KAKA_VERSION_2_DATE: 2023-01-01

ARBEID_OG_INNTEKT_URL: https://arbeid-og-inntekt.prod-fss-pub.nais.io/

KLAGE_FSS_PROXY_URL: https://klage-fss-proxy.prod-fss-pub.nais.io

OPPGAVE_API_BASE_URL: https://oppgave.prod-fss-pub.nais.io/api/v1
OPPGAVE_API_SCOPE: prod-fss.oppgavehandtering.oppgave

FSS_CLUSTER: prod-fss

SETTINGS_CLEANUP_CRON: 0 15 16 * * WED