package no.nav.klage.oppgave.domain.klage

enum class BehandlingStatus {
    IKKE_TILDELT, TILDELT, MEDUNDERSKRIVER_VALGT, SENDT_TIL_MEDUNDERSKRIVER, RETURNERT_TIL_SAKSBEHANDLER, PAA_VENT, ANDRE_BEHANDLING, AVSLUTTET_AV_SAKSBEHANDLER, FULLFOERT, UKJENT

}