ingress: https://klage-oppgave-api.dev.nav.no
externalHosts:
  - login.microsoftonline.com
  - hooks.slack.com
  - unleash.nais.io
  - klage-fss-proxy.dev-fss-pub.nais.io
springProfile: dev-gcp
tenant: trygdeetaten.no
db_tier: db-custom-1-3840
db_size: 10
db_ha: true