pool: nav-prod
config:
  cleanupPolicy: delete
  minimumInSyncReplicas: 1
  partitions: 1
  replication: 3
  retentionBytes: -1
  retentionHours: 24
acl:
  - team: klage
    application: klage-kafka-manager
    access: read