UPDATE klage.behandling
SET dvh_referanse = '48270708'
WHERE kilde_referanse = '51465082'
  AND dvh_referanse = '36263910';

UPDATE klage.behandling
SET dato_mottatt_klageinstans = '2024-02-07 00:00:00.000000'
WHERE kilde_referanse = '51465082'
  AND dvh_referanse = '48270708';

INSERT INTO klage.behandling(id, klager_type, klager_value, prosessfullmektig_type, prosessfullmektig_value,
                             saken_gjelder_type, saken_gjelder_value, tema_id, type_id, kilde_referanse, sak_fagsystem,
                             sak_fagsak_id, dato_mottatt_foersteinstans, dato_mottatt_klageinstans,
                             dato_behandling_tildelt, frist, tildelt_saksbehandlerident, tildelt_enhet,
                             avsender_enhet_foersteinstans, previous_saksbehandlerident, mottak_id,
                             kommentar_fra_foersteinstans, created, modified, medunderskriver_enhet,
                             kaka_kvalitetsvurdering_id, ytelse_id, dvh_referanse, behandling_type, klage_vedtaks_dato,
                             klage_behandlende_enhet, source_behandling_id, satt_paa_vent_from, sendt_til_trygderetten,
                             kjennelse_mottatt, kaka_kvalitetsvurdering_version, feilregistrering_nav_ident,
                             feilregistrering_registered, feilregistrering_reason, feilregistrering_fagsystem_id,
                             satt_paa_vent_to, satt_paa_vent_reason, utfall_id,
                             dato_behandling_avsluttet_av_saksbehandler, dato_behandling_avsluttet,
                             medunderskriverident, dato_sendt_medunderskriver, medunderskriver_flow_state_id, rol_ident,
                             rol_flow_state_id, ny_ankebehandling_ka, rol_returned_date, gosys_oppgave_id,
                             varslet_frist, varslet_behandlingstid_units, varslet_behandlingstid_unit_type_id,
                             feilregistrering_navn, ferdigstilling_nav_ident, ferdigstilling_navn,
                             oppgave_returned_tildelt_enhetsnummer, oppgave_returned_mappe_id,
                             oppgave_returned_kommentar, ny_behandling_etter_tr_opphevet, anke_behandlende_enhet,
                             tilbakekreving, ignore_gosys_oppgave, prosessfullmektig_navn,
                             prosessfullmektig_address_adressetype, prosessfullmektig_address_adresselinje_1,
                             prosessfullmektig_address_adresselinje_2, prosessfullmektig_address_adresselinje_3,
                             prosessfullmektig_address_postnummer, prosessfullmektig_address_poststed,
                             prosessfullmektig_address_landkode)
VALUES (
        gen_random_uuid(),
        'PERSON',
        '26126625153',
        null,
        null,
        'PERSON',
        '26126625153',
        null,
        '3',
    '51465082',
        '11',
        '24617749',
        null,
        '2024-02-06 00:00:00.000000',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        now(),
        now(),
        null,
        null,
        '35',
        '48827910',
        'anke_i_trygderetten',
        null,
        null,
        null,
        null,
        '2024-07-29 18:44:47.000000',
        null,
        '1',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '1',
        null,
        '1',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        '4291',
        false,
        false,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
       );