name: Deploy kafka topics

on:
  push:
    branches:
      - main
    paths:
      - kafka-aiven/**
      - '!kafka-aiven/README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy vedtak-fattet-topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/vedtak-fattet.v1/topic.yaml
          VARS: kafka-aiven/vedtak-fattet.v1/dev-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy dvh-topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/kabal-statistikk.v1/topic.yaml
          VARS: kafka-aiven/kabal-statistikk.v1/dev-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy klage-endret-topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/klage-endret.v1/topic.yaml
          VARS: kafka-aiven/klage-endret.v1/dev-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy behandling-endret-v2-topic to dev
          uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
            CLUSTER: dev-gcp
            RESOURCE: kafka-aiven/behandling-endret.v2/topic.yaml
            VARS: kafka-aiven/behandling-endret.v2/dev-vars.yaml
            PRINT_PAYLOAD: true
      - name: deploy vedtak-fattet-topic to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/vedtak-fattet.v1/topic.yaml
          VARS: kafka-aiven/vedtak-fattet.v1/prod-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy dvh-topic to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/kabal-statistikk.v1/topic.yaml
          VARS: kafka-aiven/kabal-statistikk.v1/prod-vars.yaml
          PRINT_PAYLOAD: true
      - name: deploy klage-endret-topic to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: prod-gcp
          RESOURCE: kafka-aiven/klage-endret.v1/topic.yaml
          VARS: kafka-aiven/klage-endret.v1/prod-vars.yaml
          PRINT_PAYLOAD: true
#      - name: deploy behandling-endret-v2-topic to prod
#          uses: nais/deploy/actions/deploy@v1
#          env:
#            APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
#            CLUSTER: prod-gcp
#            RESOURCE: kafka-aiven/behandling-endret.v2/topic.yaml
#            VARS: kafka-aiven/behandling-endret.v2/prod-vars.yaml
#            PRINT_PAYLOAD: true
