name: Deploy kafka topics

on:
  push:
    branches:
      - main
    paths:
      - kafka-aiven/**
      - '!kafka-aiven/README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [dev, prod]
        topic: [behandling-endret.v2, behandling-events.v1, kabal-statistikk.v1, internal-events.v1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy kafka-topic ${{ matrix.topic }} to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: kafka-aiven/${{ matrix.topic }}/topic.yaml
          VARS: kafka-aiven/${{ matrix.topic }}/${{ matrix.cluster }}-vars.yaml
          PRINT_PAYLOAD: true
